/* Automatically generated by tree-sitter v0.25.1 (f5afe475deb7c0bae6407fb776c76824f717bb61) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 21
#define SYMBOL_COUNT 35
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LPAREN = 1,
  anon_sym_RPAREN = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  sym_identifier = 5,
  sym_number = 6,
  sym_string = 7,
  anon_sym_PIPE_GT = 8,
  anon_sym_DASH_GT = 9,
  anon_sym_COLON_GT = 10,
  anon_sym_BANG_GT = 11,
  anon_sym_LT_BANG = 12,
  anon_sym_LT_COLON = 13,
  anon_sym_LT_DASH = 14,
  anon_sym_LT_PIPE = 15,
  anon_sym_GT = 16,
  anon_sym_LT = 17,
  anon_sym_EQ = 18,
  anon_sym_COMMA = 19,
  anon_sym_DOT = 20,
  anon_sym_SEMI = 21,
  sym_op = 22,
  sym_source_file = 23,
  sym_expression = 24,
  sym__term = 25,
  sym_operator_expression = 26,
  sym_parenthetical_expression = 27,
  sym_curly_expression = 28,
  sym_opcurry = 29,
  sym_apply = 30,
  sym_st_op = 31,
  sym_main_op = 32,
  aux_sym_opcurry_repeat1 = 33,
  aux_sym_apply_repeat1 = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_PIPE_GT] = "|>",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_COLON_GT] = ":>",
  [anon_sym_BANG_GT] = "!>",
  [anon_sym_LT_BANG] = "<!",
  [anon_sym_LT_COLON] = "<:",
  [anon_sym_LT_DASH] = "<-",
  [anon_sym_LT_PIPE] = "<|",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [anon_sym_SEMI] = ";",
  [sym_op] = "op",
  [sym_source_file] = "source_file",
  [sym_expression] = "expression",
  [sym__term] = "_term",
  [sym_operator_expression] = "operator_expression",
  [sym_parenthetical_expression] = "parenthetical_expression",
  [sym_curly_expression] = "curly_expression",
  [sym_opcurry] = "opcurry",
  [sym_apply] = "apply",
  [sym_st_op] = "st_op",
  [sym_main_op] = "main_op",
  [aux_sym_opcurry_repeat1] = "opcurry_repeat1",
  [aux_sym_apply_repeat1] = "apply_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_PIPE_GT] = anon_sym_PIPE_GT,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_COLON_GT] = anon_sym_COLON_GT,
  [anon_sym_BANG_GT] = anon_sym_BANG_GT,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [anon_sym_LT_COLON] = anon_sym_LT_COLON,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [anon_sym_LT_PIPE] = anon_sym_LT_PIPE,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_op] = sym_op,
  [sym_source_file] = sym_source_file,
  [sym_expression] = sym_expression,
  [sym__term] = sym__term,
  [sym_operator_expression] = sym_operator_expression,
  [sym_parenthetical_expression] = sym_parenthetical_expression,
  [sym_curly_expression] = sym_curly_expression,
  [sym_opcurry] = sym_opcurry,
  [sym_apply] = sym_apply,
  [sym_st_op] = sym_st_op,
  [sym_main_op] = sym_main_op,
  [aux_sym_opcurry_repeat1] = aux_sym_opcurry_repeat1,
  [aux_sym_apply_repeat1] = aux_sym_apply_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_op] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__term] = {
    .visible = false,
    .named = true,
  },
  [sym_operator_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthetical_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_curly_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_opcurry] = {
    .visible = true,
    .named = true,
  },
  [sym_apply] = {
    .visible = true,
    .named = true,
  },
  [sym_st_op] = {
    .visible = true,
    .named = true,
  },
  [sym_main_op] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_opcurry_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_apply_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 4,
  [8] = 5,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 12,
  [16] = 16,
  [17] = 17,
  [18] = 13,
  [19] = 19,
  [20] = 14,
  [21] = 21,
  [22] = 22,
  [23] = 21,
  [24] = 24,
  [25] = 24,
  [26] = 26,
  [27] = 27,
  [28] = 27,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '!', 28,
        '"', 27,
        '(', 5,
        ')', 6,
        ',', 23,
        '-', 29,
        '.', 24,
        ':', 30,
        ';', 25,
        '<', 21,
        '=', 22,
        '>', 20,
        '{', 7,
        '|', 31,
        '}', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(11);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '!', 28,
        ')', 6,
        ',', 23,
        '-', 29,
        '.', 24,
        ':', 30,
        ';', 25,
        '<', 21,
        '=', 22,
        '>', 20,
        '|', 31,
        '}', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          (lookahead < '0' || '>' < lookahead) &&
          (lookahead < 'A' || 'Z' < lookahead) &&
          lookahead != '_' &&
          (lookahead < 'a' || '}' < lookahead)) ADVANCE(26);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_PIPE_GT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COLON_GT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_BANG_GT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LT_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LT_PIPE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(16);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == '|') ADVANCE(19);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_op);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_op);
      if (lookahead == '"') ADVANCE(11);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_op);
      if (lookahead == '>') ADVANCE(15);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_op);
      if (lookahead == '>') ADVANCE(13);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_op);
      if (lookahead == '>') ADVANCE(14);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_op);
      if (lookahead == '>') ADVANCE(12);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_PIPE_GT] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_COLON_GT] = ACTIONS(1),
    [anon_sym_BANG_GT] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_LT_COLON] = ACTIONS(1),
    [anon_sym_LT_DASH] = ACTIONS(1),
    [anon_sym_LT_PIPE] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_op] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(32),
    [sym_expression] = STATE(19),
    [sym__term] = STATE(4),
    [sym_operator_expression] = STATE(20),
    [sym_parenthetical_expression] = STATE(4),
    [sym_curly_expression] = STATE(4),
    [sym_opcurry] = STATE(20),
    [sym_apply] = STATE(20),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_number] = ACTIONS(7),
    [sym_string] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_expression] = STATE(17),
    [sym__term] = STATE(4),
    [sym_operator_expression] = STATE(20),
    [sym_parenthetical_expression] = STATE(4),
    [sym_curly_expression] = STATE(4),
    [sym_opcurry] = STATE(20),
    [sym_apply] = STATE(20),
    [sym_st_op] = STATE(24),
    [sym_main_op] = STATE(24),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_number] = ACTIONS(7),
    [sym_string] = ACTIONS(7),
    [anon_sym_PIPE_GT] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_COLON_GT] = ACTIONS(9),
    [anon_sym_BANG_GT] = ACTIONS(9),
    [anon_sym_LT_BANG] = ACTIONS(9),
    [anon_sym_LT_COLON] = ACTIONS(9),
    [anon_sym_LT_DASH] = ACTIONS(9),
    [anon_sym_LT_PIPE] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_SEMI] = ACTIONS(13),
    [sym_op] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym_expression] = STATE(17),
    [sym__term] = STATE(4),
    [sym_operator_expression] = STATE(20),
    [sym_parenthetical_expression] = STATE(4),
    [sym_curly_expression] = STATE(4),
    [sym_opcurry] = STATE(20),
    [sym_apply] = STATE(20),
    [sym_st_op] = STATE(25),
    [sym_main_op] = STATE(25),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_number] = ACTIONS(7),
    [sym_string] = ACTIONS(7),
    [anon_sym_PIPE_GT] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_COLON_GT] = ACTIONS(9),
    [anon_sym_BANG_GT] = ACTIONS(9),
    [anon_sym_LT_BANG] = ACTIONS(9),
    [anon_sym_LT_COLON] = ACTIONS(9),
    [anon_sym_LT_DASH] = ACTIONS(9),
    [anon_sym_LT_PIPE] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_SEMI] = ACTIONS(13),
    [sym_op] = ACTIONS(17),
  },
  [STATE(4)] = {
    [sym__term] = STATE(5),
    [sym_parenthetical_expression] = STATE(5),
    [sym_curly_expression] = STATE(5),
    [aux_sym_apply_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(19),
    [sym_identifier] = ACTIONS(23),
    [sym_number] = ACTIONS(23),
    [sym_string] = ACTIONS(23),
    [anon_sym_PIPE_GT] = ACTIONS(19),
    [anon_sym_DASH_GT] = ACTIONS(19),
    [anon_sym_COLON_GT] = ACTIONS(19),
    [anon_sym_BANG_GT] = ACTIONS(19),
    [anon_sym_LT_BANG] = ACTIONS(19),
    [anon_sym_LT_COLON] = ACTIONS(19),
    [anon_sym_LT_DASH] = ACTIONS(19),
    [anon_sym_LT_PIPE] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(19),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_EQ] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_DOT] = ACTIONS(19),
    [anon_sym_SEMI] = ACTIONS(19),
    [sym_op] = ACTIONS(25),
  },
  [STATE(5)] = {
    [sym__term] = STATE(6),
    [sym_parenthetical_expression] = STATE(6),
    [sym_curly_expression] = STATE(6),
    [aux_sym_apply_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(27),
    [sym_identifier] = ACTIONS(29),
    [sym_number] = ACTIONS(29),
    [sym_string] = ACTIONS(29),
    [anon_sym_PIPE_GT] = ACTIONS(27),
    [anon_sym_DASH_GT] = ACTIONS(27),
    [anon_sym_COLON_GT] = ACTIONS(27),
    [anon_sym_BANG_GT] = ACTIONS(27),
    [anon_sym_LT_BANG] = ACTIONS(27),
    [anon_sym_LT_COLON] = ACTIONS(27),
    [anon_sym_LT_DASH] = ACTIONS(27),
    [anon_sym_LT_PIPE] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(31),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_COMMA] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [sym_op] = ACTIONS(31),
  },
  [STATE(6)] = {
    [sym__term] = STATE(6),
    [sym_parenthetical_expression] = STATE(6),
    [sym_curly_expression] = STATE(6),
    [aux_sym_apply_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(33),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_RPAREN] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(38),
    [anon_sym_RBRACE] = ACTIONS(33),
    [sym_identifier] = ACTIONS(41),
    [sym_number] = ACTIONS(41),
    [sym_string] = ACTIONS(41),
    [anon_sym_PIPE_GT] = ACTIONS(33),
    [anon_sym_DASH_GT] = ACTIONS(33),
    [anon_sym_COLON_GT] = ACTIONS(33),
    [anon_sym_BANG_GT] = ACTIONS(33),
    [anon_sym_LT_BANG] = ACTIONS(33),
    [anon_sym_LT_COLON] = ACTIONS(33),
    [anon_sym_LT_DASH] = ACTIONS(33),
    [anon_sym_LT_PIPE] = ACTIONS(33),
    [anon_sym_GT] = ACTIONS(33),
    [anon_sym_LT] = ACTIONS(44),
    [anon_sym_EQ] = ACTIONS(33),
    [anon_sym_COMMA] = ACTIONS(33),
    [anon_sym_DOT] = ACTIONS(33),
    [anon_sym_SEMI] = ACTIONS(33),
    [sym_op] = ACTIONS(44),
  },
  [STATE(7)] = {
    [sym__term] = STATE(8),
    [sym_parenthetical_expression] = STATE(8),
    [sym_curly_expression] = STATE(8),
    [aux_sym_apply_repeat1] = STATE(8),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(5),
    [sym_identifier] = ACTIONS(46),
    [sym_number] = ACTIONS(46),
    [sym_string] = ACTIONS(46),
    [anon_sym_PIPE_GT] = ACTIONS(19),
    [anon_sym_DASH_GT] = ACTIONS(19),
    [anon_sym_COLON_GT] = ACTIONS(19),
    [anon_sym_BANG_GT] = ACTIONS(19),
    [anon_sym_LT_BANG] = ACTIONS(19),
    [anon_sym_LT_COLON] = ACTIONS(19),
    [anon_sym_LT_DASH] = ACTIONS(19),
    [anon_sym_LT_PIPE] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(19),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_EQ] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_DOT] = ACTIONS(19),
    [anon_sym_SEMI] = ACTIONS(19),
    [sym_op] = ACTIONS(25),
  },
  [STATE(8)] = {
    [sym__term] = STATE(6),
    [sym_parenthetical_expression] = STATE(6),
    [sym_curly_expression] = STATE(6),
    [aux_sym_apply_repeat1] = STATE(6),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(27),
    [sym_identifier] = ACTIONS(27),
    [sym_number] = ACTIONS(27),
    [sym_string] = ACTIONS(27),
    [anon_sym_PIPE_GT] = ACTIONS(27),
    [anon_sym_DASH_GT] = ACTIONS(27),
    [anon_sym_COLON_GT] = ACTIONS(27),
    [anon_sym_BANG_GT] = ACTIONS(27),
    [anon_sym_LT_BANG] = ACTIONS(27),
    [anon_sym_LT_COLON] = ACTIONS(27),
    [anon_sym_LT_DASH] = ACTIONS(27),
    [anon_sym_LT_PIPE] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(31),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_COMMA] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [sym_op] = ACTIONS(31),
  },
  [STATE(9)] = {
    [sym_st_op] = STATE(28),
    [sym_main_op] = STATE(28),
    [anon_sym_LPAREN] = ACTIONS(48),
    [anon_sym_RPAREN] = ACTIONS(48),
    [anon_sym_LBRACE] = ACTIONS(48),
    [sym_identifier] = ACTIONS(48),
    [sym_number] = ACTIONS(48),
    [sym_string] = ACTIONS(48),
    [anon_sym_PIPE_GT] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_COLON_GT] = ACTIONS(9),
    [anon_sym_BANG_GT] = ACTIONS(9),
    [anon_sym_LT_BANG] = ACTIONS(9),
    [anon_sym_LT_COLON] = ACTIONS(9),
    [anon_sym_LT_DASH] = ACTIONS(9),
    [anon_sym_LT_PIPE] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_SEMI] = ACTIONS(13),
    [sym_op] = ACTIONS(50),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(52),
    [anon_sym_LPAREN] = ACTIONS(52),
    [anon_sym_RPAREN] = ACTIONS(52),
    [anon_sym_LBRACE] = ACTIONS(52),
    [anon_sym_RBRACE] = ACTIONS(52),
    [sym_identifier] = ACTIONS(52),
    [sym_number] = ACTIONS(52),
    [sym_string] = ACTIONS(52),
    [anon_sym_PIPE_GT] = ACTIONS(52),
    [anon_sym_DASH_GT] = ACTIONS(52),
    [anon_sym_COLON_GT] = ACTIONS(52),
    [anon_sym_BANG_GT] = ACTIONS(52),
    [anon_sym_LT_BANG] = ACTIONS(52),
    [anon_sym_LT_COLON] = ACTIONS(52),
    [anon_sym_LT_DASH] = ACTIONS(52),
    [anon_sym_LT_PIPE] = ACTIONS(52),
    [anon_sym_GT] = ACTIONS(52),
    [anon_sym_LT] = ACTIONS(54),
    [anon_sym_EQ] = ACTIONS(52),
    [anon_sym_COMMA] = ACTIONS(52),
    [anon_sym_DOT] = ACTIONS(52),
    [anon_sym_SEMI] = ACTIONS(52),
    [sym_op] = ACTIONS(54),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(56),
    [anon_sym_LPAREN] = ACTIONS(56),
    [anon_sym_RPAREN] = ACTIONS(56),
    [anon_sym_LBRACE] = ACTIONS(56),
    [anon_sym_RBRACE] = ACTIONS(56),
    [sym_identifier] = ACTIONS(56),
    [sym_number] = ACTIONS(56),
    [sym_string] = ACTIONS(56),
    [anon_sym_PIPE_GT] = ACTIONS(56),
    [anon_sym_DASH_GT] = ACTIONS(56),
    [anon_sym_COLON_GT] = ACTIONS(56),
    [anon_sym_BANG_GT] = ACTIONS(56),
    [anon_sym_LT_BANG] = ACTIONS(56),
    [anon_sym_LT_COLON] = ACTIONS(56),
    [anon_sym_LT_DASH] = ACTIONS(56),
    [anon_sym_LT_PIPE] = ACTIONS(56),
    [anon_sym_GT] = ACTIONS(56),
    [anon_sym_LT] = ACTIONS(58),
    [anon_sym_EQ] = ACTIONS(56),
    [anon_sym_COMMA] = ACTIONS(56),
    [anon_sym_DOT] = ACTIONS(56),
    [anon_sym_SEMI] = ACTIONS(56),
    [sym_op] = ACTIONS(58),
  },
  [STATE(12)] = {
    [sym_st_op] = STATE(28),
    [sym_main_op] = STATE(28),
    [anon_sym_LPAREN] = ACTIONS(60),
    [anon_sym_RPAREN] = ACTIONS(60),
    [anon_sym_LBRACE] = ACTIONS(60),
    [sym_identifier] = ACTIONS(60),
    [sym_number] = ACTIONS(60),
    [sym_string] = ACTIONS(60),
    [anon_sym_PIPE_GT] = ACTIONS(60),
    [anon_sym_DASH_GT] = ACTIONS(60),
    [anon_sym_COLON_GT] = ACTIONS(60),
    [anon_sym_BANG_GT] = ACTIONS(60),
    [anon_sym_LT_BANG] = ACTIONS(60),
    [anon_sym_LT_COLON] = ACTIONS(60),
    [anon_sym_LT_DASH] = ACTIONS(60),
    [anon_sym_LT_PIPE] = ACTIONS(60),
    [anon_sym_GT] = ACTIONS(60),
    [anon_sym_LT] = ACTIONS(62),
    [anon_sym_EQ] = ACTIONS(60),
    [anon_sym_COMMA] = ACTIONS(60),
    [anon_sym_DOT] = ACTIONS(60),
    [anon_sym_SEMI] = ACTIONS(60),
    [sym_op] = ACTIONS(62),
  },
  [STATE(13)] = {
    [anon_sym_LPAREN] = ACTIONS(64),
    [anon_sym_RPAREN] = ACTIONS(64),
    [anon_sym_LBRACE] = ACTIONS(64),
    [sym_identifier] = ACTIONS(64),
    [sym_number] = ACTIONS(64),
    [sym_string] = ACTIONS(64),
    [anon_sym_PIPE_GT] = ACTIONS(64),
    [anon_sym_DASH_GT] = ACTIONS(64),
    [anon_sym_COLON_GT] = ACTIONS(64),
    [anon_sym_BANG_GT] = ACTIONS(64),
    [anon_sym_LT_BANG] = ACTIONS(64),
    [anon_sym_LT_COLON] = ACTIONS(64),
    [anon_sym_LT_DASH] = ACTIONS(64),
    [anon_sym_LT_PIPE] = ACTIONS(64),
    [anon_sym_GT] = ACTIONS(64),
    [anon_sym_LT] = ACTIONS(66),
    [anon_sym_EQ] = ACTIONS(64),
    [anon_sym_COMMA] = ACTIONS(64),
    [anon_sym_DOT] = ACTIONS(64),
    [anon_sym_SEMI] = ACTIONS(64),
    [sym_op] = ACTIONS(66),
  },
  [STATE(14)] = {
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_RPAREN] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(19),
    [sym_identifier] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_PIPE_GT] = ACTIONS(19),
    [anon_sym_DASH_GT] = ACTIONS(19),
    [anon_sym_COLON_GT] = ACTIONS(19),
    [anon_sym_BANG_GT] = ACTIONS(19),
    [anon_sym_LT_BANG] = ACTIONS(19),
    [anon_sym_LT_COLON] = ACTIONS(19),
    [anon_sym_LT_DASH] = ACTIONS(19),
    [anon_sym_LT_PIPE] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(19),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_EQ] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_DOT] = ACTIONS(19),
    [anon_sym_SEMI] = ACTIONS(19),
    [sym_op] = ACTIONS(25),
  },
  [STATE(15)] = {
    [sym_st_op] = STATE(27),
    [sym_main_op] = STATE(27),
    [ts_builtin_sym_end] = ACTIONS(60),
    [anon_sym_RPAREN] = ACTIONS(60),
    [anon_sym_RBRACE] = ACTIONS(60),
    [anon_sym_PIPE_GT] = ACTIONS(60),
    [anon_sym_DASH_GT] = ACTIONS(60),
    [anon_sym_COLON_GT] = ACTIONS(60),
    [anon_sym_BANG_GT] = ACTIONS(60),
    [anon_sym_LT_BANG] = ACTIONS(60),
    [anon_sym_LT_COLON] = ACTIONS(60),
    [anon_sym_LT_DASH] = ACTIONS(60),
    [anon_sym_LT_PIPE] = ACTIONS(60),
    [anon_sym_GT] = ACTIONS(60),
    [anon_sym_LT] = ACTIONS(62),
    [anon_sym_EQ] = ACTIONS(60),
    [anon_sym_COMMA] = ACTIONS(60),
    [anon_sym_DOT] = ACTIONS(60),
    [anon_sym_SEMI] = ACTIONS(60),
    [sym_op] = ACTIONS(62),
  },
  [STATE(16)] = {
    [sym_st_op] = STATE(27),
    [sym_main_op] = STATE(27),
    [anon_sym_RBRACE] = ACTIONS(68),
    [anon_sym_PIPE_GT] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_COLON_GT] = ACTIONS(9),
    [anon_sym_BANG_GT] = ACTIONS(9),
    [anon_sym_LT_BANG] = ACTIONS(9),
    [anon_sym_LT_COLON] = ACTIONS(9),
    [anon_sym_LT_DASH] = ACTIONS(9),
    [anon_sym_LT_PIPE] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_SEMI] = ACTIONS(13),
    [sym_op] = ACTIONS(70),
  },
  [STATE(17)] = {
    [sym_st_op] = STATE(27),
    [sym_main_op] = STATE(27),
    [anon_sym_RPAREN] = ACTIONS(72),
    [anon_sym_PIPE_GT] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_COLON_GT] = ACTIONS(9),
    [anon_sym_BANG_GT] = ACTIONS(9),
    [anon_sym_LT_BANG] = ACTIONS(9),
    [anon_sym_LT_COLON] = ACTIONS(9),
    [anon_sym_LT_DASH] = ACTIONS(9),
    [anon_sym_LT_PIPE] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_SEMI] = ACTIONS(13),
    [sym_op] = ACTIONS(70),
  },
  [STATE(18)] = {
    [ts_builtin_sym_end] = ACTIONS(64),
    [anon_sym_RPAREN] = ACTIONS(64),
    [anon_sym_RBRACE] = ACTIONS(64),
    [anon_sym_PIPE_GT] = ACTIONS(64),
    [anon_sym_DASH_GT] = ACTIONS(64),
    [anon_sym_COLON_GT] = ACTIONS(64),
    [anon_sym_BANG_GT] = ACTIONS(64),
    [anon_sym_LT_BANG] = ACTIONS(64),
    [anon_sym_LT_COLON] = ACTIONS(64),
    [anon_sym_LT_DASH] = ACTIONS(64),
    [anon_sym_LT_PIPE] = ACTIONS(64),
    [anon_sym_GT] = ACTIONS(64),
    [anon_sym_LT] = ACTIONS(66),
    [anon_sym_EQ] = ACTIONS(64),
    [anon_sym_COMMA] = ACTIONS(64),
    [anon_sym_DOT] = ACTIONS(64),
    [anon_sym_SEMI] = ACTIONS(64),
    [sym_op] = ACTIONS(66),
  },
  [STATE(19)] = {
    [sym_st_op] = STATE(27),
    [sym_main_op] = STATE(27),
    [ts_builtin_sym_end] = ACTIONS(74),
    [anon_sym_PIPE_GT] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_COLON_GT] = ACTIONS(9),
    [anon_sym_BANG_GT] = ACTIONS(9),
    [anon_sym_LT_BANG] = ACTIONS(9),
    [anon_sym_LT_COLON] = ACTIONS(9),
    [anon_sym_LT_DASH] = ACTIONS(9),
    [anon_sym_LT_PIPE] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_SEMI] = ACTIONS(13),
    [sym_op] = ACTIONS(70),
  },
  [STATE(20)] = {
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_RPAREN] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(19),
    [anon_sym_PIPE_GT] = ACTIONS(19),
    [anon_sym_DASH_GT] = ACTIONS(19),
    [anon_sym_COLON_GT] = ACTIONS(19),
    [anon_sym_BANG_GT] = ACTIONS(19),
    [anon_sym_LT_BANG] = ACTIONS(19),
    [anon_sym_LT_COLON] = ACTIONS(19),
    [anon_sym_LT_DASH] = ACTIONS(19),
    [anon_sym_LT_PIPE] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(19),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_EQ] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(19),
    [anon_sym_DOT] = ACTIONS(19),
    [anon_sym_SEMI] = ACTIONS(19),
    [sym_op] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(76), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      anon_sym_RPAREN,
    STATE(9), 1,
      sym_expression,
    STATE(22), 1,
      aux_sym_opcurry_repeat1,
    ACTIONS(80), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(7), 3,
      sym__term,
      sym_parenthetical_expression,
      sym_curly_expression,
    STATE(14), 3,
      sym_operator_expression,
      sym_opcurry,
      sym_apply,
  [31] = 8,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    ACTIONS(87), 1,
      anon_sym_LBRACE,
    STATE(9), 1,
      sym_expression,
    STATE(22), 1,
      aux_sym_opcurry_repeat1,
    ACTIONS(90), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(7), 3,
      sym__term,
      sym_parenthetical_expression,
      sym_curly_expression,
    STATE(14), 3,
      sym_operator_expression,
      sym_opcurry,
      sym_apply,
  [62] = 8,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(76), 1,
      anon_sym_LPAREN,
    ACTIONS(93), 1,
      anon_sym_RPAREN,
    STATE(9), 1,
      sym_expression,
    STATE(22), 1,
      aux_sym_opcurry_repeat1,
    ACTIONS(80), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(7), 3,
      sym__term,
      sym_parenthetical_expression,
      sym_curly_expression,
    STATE(14), 3,
      sym_operator_expression,
      sym_opcurry,
      sym_apply,
  [93] = 7,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(76), 1,
      anon_sym_LPAREN,
    STATE(9), 1,
      sym_expression,
    STATE(21), 1,
      aux_sym_opcurry_repeat1,
    ACTIONS(80), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(7), 3,
      sym__term,
      sym_parenthetical_expression,
      sym_curly_expression,
    STATE(14), 3,
      sym_operator_expression,
      sym_opcurry,
      sym_apply,
  [121] = 7,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(76), 1,
      anon_sym_LPAREN,
    STATE(9), 1,
      sym_expression,
    STATE(23), 1,
      aux_sym_opcurry_repeat1,
    ACTIONS(80), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(7), 3,
      sym__term,
      sym_parenthetical_expression,
      sym_curly_expression,
    STATE(14), 3,
      sym_operator_expression,
      sym_opcurry,
      sym_apply,
  [149] = 6,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    STATE(17), 1,
      sym_expression,
    ACTIONS(7), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(4), 3,
      sym__term,
      sym_parenthetical_expression,
      sym_curly_expression,
    STATE(20), 3,
      sym_operator_expression,
      sym_opcurry,
      sym_apply,
  [174] = 6,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    STATE(15), 1,
      sym_expression,
    ACTIONS(7), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(4), 3,
      sym__term,
      sym_parenthetical_expression,
      sym_curly_expression,
    STATE(20), 3,
      sym_operator_expression,
      sym_opcurry,
      sym_apply,
  [199] = 6,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(76), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_expression,
    ACTIONS(80), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(7), 3,
      sym__term,
      sym_parenthetical_expression,
      sym_curly_expression,
    STATE(14), 3,
      sym_operator_expression,
      sym_opcurry,
      sym_apply,
  [224] = 6,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    STATE(16), 1,
      sym_expression,
    ACTIONS(7), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(4), 3,
      sym__term,
      sym_parenthetical_expression,
      sym_curly_expression,
    STATE(20), 3,
      sym_operator_expression,
      sym_opcurry,
      sym_apply,
  [249] = 1,
    ACTIONS(95), 5,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_identifier,
      sym_number,
      sym_string,
  [257] = 1,
    ACTIONS(97), 5,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_identifier,
      sym_number,
      sym_string,
  [265] = 1,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(21)] = 0,
  [SMALL_STATE(22)] = 31,
  [SMALL_STATE(23)] = 62,
  [SMALL_STATE(24)] = 93,
  [SMALL_STATE(25)] = 121,
  [SMALL_STATE(26)] = 149,
  [SMALL_STATE(27)] = 174,
  [SMALL_STATE(28)] = 199,
  [SMALL_STATE(29)] = 224,
  [SMALL_STATE(30)] = 249,
  [SMALL_STATE(31)] = 257,
  [SMALL_STATE(32)] = 265,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_apply, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_apply, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_opcurry_repeat1, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthetical_expression, 3, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthetical_expression, 3, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_curly_expression, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_curly_expression, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator_expression, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator_expression, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opcurry, 4, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_opcurry, 4, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_opcurry_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_opcurry_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_opcurry_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_opcurry_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_main_op, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_st_op, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_kolibri(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "kolibri",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
